In [1]:
import numpy as np

# Check NumPy version and configuration
print(np.__version__)
print(np.show_config())


1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bello/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Bello/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bello/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Bello/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bello/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Bello/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bello/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Bello/anaconda3\\Library\\include']
None


In [2]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
array_size = np.zeros(10)
print(array_size.size * array_size.itemsize)


80


In [4]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
vector_range = np.arange(10, 50)
print(vector_range)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
vector = np.arange(10)
reversed_vector = vector[::-1]
print(reversed_vector)


[9 8 7 6 5 4 3 2 1 0]


In [7]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


In [9]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
random_array = np.random.random((3, 3, 3))
print(random_array)


[[[0.43719126 0.18228834 0.69252421]
  [0.24092852 0.9943416  0.76835803]
  [0.73560703 0.21764613 0.15778521]]

 [[0.48839437 0.58663001 0.11820201]
  [0.42738135 0.98820863 0.84815721]
  [0.24937865 0.11245622 0.2117634 ]]

 [[0.7360072  0.02993958 0.0276639 ]
  [0.19299397 0.14513603 0.35115826]
  [0.45715638 0.41785583 0.54514879]]]


In [11]:
random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Minimum:", min_value)
print("Maximum:", max_value)


Minimum: 0.02012104581337415
Maximum: 0.9937565566810915
